version: 6.1.{build}
branches:
  only:
  - main
  - build-test
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore src/SystemsRx.sln
build:
  project: src/SystemsRx.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
deploy:
  provider: NuGet
  on:
    APPVEYOR_REPO_TAG: true
  server:
  api_key:
    secure: wJrG+bs2kamc9yejb3cqEmtCGrF9IcqdyU/iApCiWSofb+y69srQF5cmt9xu30/O
  skip_symbols: true
  symbol_server:
  artifact: /.*\.nupkg/
